<?xml version="1.0" encoding="UTF-8"?>
<robot rpa="false" generator="Robot 3.1.2 (Python 3.5.3 on win32)" generated="20190828 10:27:39.891">
<suite source="D:\abobo_project\robot_project\test" id="s1" name="Test">
<suite source="D:\abobo_project\robot_project\test\test01.robot" id="s1-s1" name="Test01">
<test id="s1-s1-t1" name="3">
<kw library="BuiltIn" name="Log">
<doc>Logs the given message with the given level.</doc>
<arguments>
<arg>${gaga}</arg>
</arguments>
<msg level="INFO" timestamp="20190828 10:27:40.174">Brianggkggkk开外挂kkkkkkkkkkkkkk</msg>
<status status="PASS" endtime="20190828 10:27:40.174" starttime="20190828 10:27:40.173"></status>
</kw>
<status status="PASS" endtime="20190828 10:27:40.174" critical="yes" starttime="20190828 10:27:40.173"></status>
</test>
<status status="PASS" endtime="20190828 10:27:40.174" starttime="20190828 10:27:39.929"></status>
</suite>
<status status="PASS" endtime="20190828 10:27:40.175" starttime="20190828 10:27:39.908"></status>
</suite>
<statistics>
<total>
<stat pass="1" fail="0">Critical Tests</stat>
<stat pass="1" fail="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" id="s1" fail="0" name="Test">Test</stat>
<stat pass="1" id="s1-s1" fail="0" name="Test01">Test.Test01</stat>
</suite>
</statistics>
<errors>
<msg level="ERROR" timestamp="20190828 10:27:39.906">Taking listener 'D:\abobo_project\robot_project\venv\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' into use failed: Importing listener 'D:\abobo_project\robot_project\venv\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: Creating instance failed: IndexError: tuple index out of range
Traceback (most recent call last):
  File "D:\abobo_project\robot_project\venv\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 153, in __init__
    self.port = int(args[0])</msg>
</errors>
</robot>
