<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20190828 10:25:03.451" rpa="false" generator="Robot 3.1.2 (Python 3.5.3 on win32)">
<suite id="s1" source="D:\abobo_project\robot_project\test" name="Test">
<suite id="s1-s1" source="D:\abobo_project\robot_project\test\test01.robot" name="Test01">
<test id="s1-s1-t1" name="3">
<kw library="BuiltIn" name="Log">
<doc>Logs the given message with the given level.</doc>
<arguments>
<arg>${gaga}</arg>
</arguments>
<msg level="INFO" timestamp="20190828 10:25:03.723">Brianggkggkk开外挂kkkkkkkkkkkkkk</msg>
<status starttime="20190828 10:25:03.723" status="PASS" endtime="20190828 10:25:03.723"></status>
</kw>
<status critical="yes" starttime="20190828 10:25:03.722" status="PASS" endtime="20190828 10:25:03.723"></status>
</test>
<status starttime="20190828 10:25:03.498" status="PASS" endtime="20190828 10:25:03.723"></status>
</suite>
<status starttime="20190828 10:25:03.478" status="PASS" endtime="20190828 10:25:03.724"></status>
</suite>
<statistics>
<total>
<stat pass="1" fail="0">Critical Tests</stat>
<stat pass="1" fail="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat id="s1" pass="1" fail="0" name="Test">Test</stat>
<stat id="s1-s1" pass="1" fail="0" name="Test01">Test.Test01</stat>
</suite>
</statistics>
<errors>
<msg level="ERROR" timestamp="20190828 10:25:03.473">Taking listener 'D:\abobo_project\robot_project\venv\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' into use failed: Importing listener 'D:\abobo_project\robot_project\venv\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: Creating instance failed: IndexError: tuple index out of range
Traceback (most recent call last):
  File "D:\abobo_project\robot_project\venv\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 153, in __init__
    self.port = int(args[0])</msg>
</errors>
</robot>
